---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1526596/public_html/
    - /bin/cp -R * $DEPLOTPATH
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH
    - /bin/cp .gitattributes $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .styleci.yml $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp phpunit.xml $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp server.php $DEPLOYPATH
    - /bin/cp webpack.mix.js $DEPLOYPATH	